:GUID: %guid%
:OSP_DOMAIN: dynamic.opentlc.com
:TOWER_URL: %tower_url%
:TOWER_ADMIN_USER: %tower_admin_user%
:TOWER_ADMIN_PASSWORD: %tower_admin_password%
:SSH_COMMAND: %ssh_command%
:SSH_PASSWORD: %ssh_password%
:VSCODE_UI_URL: %vscode_ui_url%
:VSCODE_UI_PASSWORD: %vscode_ui_password%
:organization_name: Default
:gitlab_project: ansible/gitops-lab
:project_prod: Project gitOps - Prod
:project_test: Project gitOps - Test
:inventory_prod: GitOps inventory - Prod Env
:inventory_test: GitOps inventory - Test Env
:credential_machine: host_credential
:credential_git: gitlab_credential
:credential_git_token: gitlab_token 
:credential_openstack: cloud_credential
:jobtemplate_prod: App deployer - Prod Env
:jobtemplate_test: App deployer - Test Env
:source-linenums-option:        
:markup-in-source: verbatim,attributes,quotes
:show_solution: tru


=== Using the `awx.awx` Collection

Your lab environment was designed to support a simple multi, or 3, tier application. 
An HAProxy instance load balancing across 2 _app servers_ running a simple python flask application with a postgresql back-end.
In this lab you will use the `awx.awx` collection to do an end to end configuration of yout *Ansible Tower* server

==== Getting Setup to Work with Ansible Tower


The `awx` cli client offers a useful way to check the next lab, and to interact with Ansible Tower.
You need to enable the repository and install it via yum.


. Setup the `awx` Tower CLI Repository

+
[source,sh]
----
$ sudo yum-config-manager --add-repo https://releases.ansible.com/ansible-tower/cli/ansible-tower-cli-el7.repo
----
+
.Sample Output
[source,texinfo]
----
adding repo from: https://releases.ansible.com/ansible-tower/cli/ansible-tower-cli-el7.repo
grabbing file https://releases.ansible.com/ansible-tower/cli/ansible-tower-cli-el7.repo to /etc/yum.repos.d/ansible-tower-cli-el7.repo
repo saved to /etc/yum.repos.d/ansible-tower-cli-el7.repo
----
+

. Install the `awx` cli

+
[source,sh]
----
$ sudo yum install -y ansible-tower-cli
----
+
.Sample Output
[source,texinfo]
----
<OUTPUT TRUNCATED>

Installed:
  ansible-tower-cli.x86_64 0:3.7.3-1.el7at                                                                                                                                                                

Dependency Installed:
  python3-PyYAML.x86_64 0:3.12-13.el7at  python3-chardet.noarch 0:3.0.4-10.el7ar  python3-idna.noarch 0:2.7-4.el7at  python3-pysocks.noarch 0:1.6.8-7.el7at  python3-requests.noarch 0:2.21.0-2.9.el7at 
  python3-six.noarch 0:1.11.0-8.el7ar    python3-urllib3.noarch 0:1.24.1-3.el7at 

----

To work with Ansible Tower there are a number of ways to authenticate: the modules support username, host, password, or API token, or a `tower_cli.cfg` file.
The `awx` cli also supports command line arguments.
In this section we will take advantage of using Shell Environmental Variables which is another approach and very flexible if you use multiple different Tower environments.
Ansible's included Tower modules, the `awx.awx` modules, and the `awx` cli support Environmental Variables.

. Export the 4 Environmental Variables `awx` needs to communicate with Ansible Tower
+

[source,bash,subs="attributes,verbatim"]
----
export TOWER_HOST=https://tower
export TOWER_USERNAME={TOWER_ADMIN_USER}
export TOWER_PASSWORD={SSH_PASSWORD}
export TOWER_VERIFY_SSL=false
----
+

. Validate your credentials and the `awx` cli by examining a Tower resource
+

[source,sh]
----
$ awx projects list -f human
----
+

.Sample Output
[source,texinfo]
----
id name         
== ============ 
6  Demo Project 
----
+

This validates that you can work with your Ansible Tower installation via the `awx` command line client.

// End of Section

=== Create the `awx.awx` Playbook

In this section we will create a number of Tower Resources using the `awx.awx` collection, so we can deploy our application.
If you are comfortable with Ansible Tower you are encouraged to create this yourself using the `ansible-doc` command to configure each task using the `awx.awx` collection.
If not a full solution is provided at the end of the section.


.Skeleton Playbook
[source,yaml]
----
---
- name: Deploy Multi Tier App to Ansible Tower using awx.awx
  hosts: localhost
  gather_facts: false
  vars: 
    cloud_user_private_file: "~/.ssh/{{ GUID }}key.pem"
    cloud_user_private_key: "{{ lookup('file', cloud_user_private_file, rstrip=false) }}"

  tasks:

  - name: Create the Flask App Project
    awx.awx.tower_project:

  - name: Create an Inventory
    awx.awx.tower_inventory:

  - name: Add Inventory Source
    awx.awx.tower_inventory_source:

  - name: Create Credential for Login
    awx.awx.tower_credential:

  - name: Create a Job Template
    awx.awx.tower_job_template:
----


* Details for `awx.awx.tower_project`

[cols="2",options="header"]
|====
| Parameter        | Value
| name             | Multitier Flask Project
| organization     | Default
| description      | AWX RHTR Collections Project
| scm_type         | git
| scm_url`         | https://github.com/tonykay/ansible_flask_app_loader_all_in_one.git
|====

* Details for `awx.awx.tower_inventory`

[cols="2",options="header"]
|====
| Parameter        | Value
| name             | Multitier Flask Inventory
| state            | present
| organization     | Default
| description      | AWX RHTR Collections Inventory
|====


* Details for `awx.awx.tower_inventory_source`

[cols="2",options="header"]
|====
|Parameter         | Value
| name             | Multitier Flask Inventory Source
| organization     | Default
| description      | AWX RHTR Collections Inventory Source
| inventory        | Multitier Flask Inventory
| source           | scm
| source_project   | Multitier Flask Project
| source_path      | hosts
| update_on_launch | true
|====

* Details for `awx.awx.tower_credential`

[cols="2",options="header"]
|====
|Parameter         | Value
| name             | MMultitier Flask Private Key
| organization     | Default
| description      | AWX RHTR Private Key
| kind             | ssh
| user_name        | cloud-user
| source_project   | Multitier Flask Project
| ssh_key_data     | "{{ cloud_user_private_key }}"
|====

* Details for `awx.awx.tower_job_template`

[cols="2",options="header"]
|====
| name             | Multitier Job Template
| project          | Multitier Flask Project
| inventory        | Multitier Flask Inventory
| playbook         | main.yml
| credentials      | Multitier Flask Private Key
|====


==== Solution

. A full solution can be viwed link:https://github.com/redhat-gpte-labs/rhtr2020_collection_lab/blob/master/resources/tower-load-flask-deployer.yml[here] and downloaded with `wget` 
+

[source,sh]
----
$ wget https://raw.githubusercontent.com/redhat-gpte-labs/rhtr2020_collection_lab/master/resources/tower-load-flask-deployer.yml
----
+

.Sample Output
[source,texinfo]
----
--2020-10-31 15:05:09--
https://raw.githubusercontent.com/redhat-gpte-labs/rhtr2020_collection_lab/master/resources/tower-load-flask-deployer.yml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.64.133, 151.101.192.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.64.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1712 (1.7K) [text/plain]
Saving to: ‘tower-load-flask-deployer.yml’
----


In the next section you will launch your Ansible Tower `job_template` and validate the results.

